In [2]:
import numpy as np

a = np.array([1,3,5])
b = np.array([2,4,6])
a * b

array([ 2, 12, 30])

# The Basics

In [39]:
a = np.array([1,3,5], dtype='int32')
print(a)

[1 3 5]


8 bits for one bytes
int32 means that the value is stored in total memory of 32 bits, which is 4 bytes

However, compared to the list, the list stores way more information that numpy. It contains 4 different things, object values, object types, reference time and size.

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
d = np.array([[[[1,2], [3,4]], [[5, 6], [7, 8]]]])
print(d)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [7]:
# Get dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
4


In [8]:
# Get shape
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


(3,)
(2, 3)
(2, 2, 2)
(1, 2, 2, 2)


**How to understand the dimensions and axes in the Numpy**  
The numpy.ndarray.ndim method can be used to check the dimensions of an array. It will return 1 for a one-dimensional array and 2 for a two-dimensional array.

**How to understand the term "shape"?**  
In this context, "shape" refers to the dimensions of an array and the number of elements in each dimension.
If .shape returns (5,), it means that the array is one-dimensional and has 5 elements.
If .shape returns (3, 6), it means that the array is two-dimensional, with 3 elements in the first dimension and 6 elements in the second dimension.
If .shape returns (2, 4, 3), it means that the array is three-dimensional, with 2 elements in the first dimension, 4 elements in the second dimension, and 3 elements in the third dimension.




### **Understanding a one-dimensional array**  
First, create a one-dimensional array 'test' with the following content: [0 1 2 3]

```python
import numpy as np
test = np.array(list([0,1,2,3]))
print(test)

output：
[0 1 2 3]
```

A one-dimensional array is relatively easy to understand. You can imagine it as a horizontal coordinate axis, where the integer coordinates on the axis correspond to the indices of the array.

![image=1d_shape](image/1d_shape.jpg)

Code verification:

Using code, we can check the dimensions and shape of array 'test'. We can also access the element at index 2 of array 'test' and anticipate it to be 2.

In [9]:
test = np.array([0, 1, 2, 3])
print(test)

print('The dimension of arraay test:', test.ndim)
print('The shape of the array test:', test.shape)
print('The index of 2 in array test:', test[2])

[0 1 2 3]
The dimension of arraay test: 1
The shape of the array test: (4,)
The index of 2 in array test: 2


### **Understanding a two-dimensional array**
First, create a two-dimensional array 'test1' with the following content:   
[0 1 2 3]  
[4 5 6 7]

```python
test1 = np.array(range(8)).reshape((2,4))
print(test1)
test1

output：
[[0 1 2 3]
 [4 5 6 7]]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
```       

![image=2d_shape.png](image/2d_shape.jpg)


You can see that in the code above, I used both print(test1) and test1. The output results of these two methods are different.

You can understand it in the following way: the result of print(test1) is for human readability, and it displays the internal contents of the array. From the output, you can see that the array test1 actually contains two lists.

On the other hand, when you directly use test1, the output result can be understood as what the computer sees, and it displays the actual content of the array itself.

This distinction helps in understanding that print(test1) provides a more detailed representation of the array's internal structure, while test1 on its own represents the content of the array as a whole.

In [10]:
test1 = np.array(range(8)).reshape((2,4))
print(test1)
test1

[[0 1 2 3]
 [4 5 6 7]]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
print('The dimension of arraay test1:', test1.ndim)
print('The shape of the array test1:', test1.shape)
print(test1[1,2])


The dimension of arraay test1: 2
The shape of the array test1: (2, 4)
6


### **To understand a three-dimensional array**  
let's create a three-dimensional array test2 with the following content:

[[[ 0 1 2 3]

[ 4 5 6 7]]



[[ 8 9 10 11]

[12 13 14 15]]



[[16 17 18 19]

[20 21 22 23]]]

```python
test2 = np.array(range(24)).reshape((3,2,4))
print(test2)

output：
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
```
<!-- ![image=3d_shape.jpg](image/3d_shape.jpg) -->
<img src="image/3d_shape.jpg" width=50% height=50%>


In [15]:
test2 = np.array(range(24)).reshape((3,2,4))
print(test2)

print('\n')

print('The dimension of arraay test2:', test2.ndim)
print('The shape of the array test2:', test2.shape)
print(test2[2,1,3])
print(test2[2,1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


The dimension of arraay test2: 3
The shape of the array test2: (3, 2, 4)
23
[20 21 22 23]


In [16]:
# Get type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int16
float64
int32


In [17]:
# Get item size, which means how many bytes each element takes up
print(a.itemsize) # 2 bytes
print(b.itemsize) # 8 bytes
print(c.itemsize) # 4 bytes

2
8
4


In [27]:
# Get the total size
print(a.size * a.itemsize) # 6 bytes
print(b.size * b.itemsize) # 48 bytes
print(c.size * c.itemsize) # 32 bytes
print('\n')
# another way to get total size
print(a.nbytes) # 6 bytes
print(b.nbytes) # 48 bytes
print(c.nbytes) # 32 bytes

6
48
32


6
48
32


# Accessing/Changing specific elements, rows, columns, etc.

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.shape

(2, 7)

In [22]:
# Get a specific element [r, c]
a[1, 5] # 13
a[1, -2] # 13

13

In [23]:
# Get a specific row
a[0, :] # [1, 2, 3, 4, 5, 6, 7]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [27]:
# Getting a little more fancy [strartindedx:endindex:stepsize]
a[0, 1:6:2] # [2, 4, 6]
a[0, 1::2] # [2, 4, 6]
a[0, 1:-1:2] # [2, 4, 6]    

array([2, 4, 6])

In [28]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [30]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Get specific element (work outside in)
b[0,1,1] # 4
b[:,0,0] 

array([1, 5])

In [32]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different types of arrays

In [33]:
# All 0s matrtix
np.zeros(5)
np.zeros((2,3))
np.zeros((2,3,3))
np.zeros((2,3,3,2))


array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [34]:
# All 1s matrix
np.ones((4,2,2), dtype ='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [36]:
# Any other number 
np.full((2,2,3), 99, dtype='float32') # shape, number

array([[[99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.]]], dtype=float32)

In [27]:
# Any other number (full_like)
np.full_like(a.shape, 4)
np.full_like((3,), 4)

# they are the same
np.full_like(a, 4) # array_like, number
np.full(a.shape, 4)



array([4, 4, 4])

In [43]:
# Random decimal numbers
# random numbers between 0 and 1
np.random.rand(4,2,3) # shape
print(np.random.rand(4,2,3)) # shape

print('\n')

# if you wanna pass a shape parameter
np.random.random_sample(a.shape)
print(np.random.random_sample(a.shape)) 

[[[0.10725192 0.43613933 0.09216238]
  [0.25757317 0.01680368 0.13693463]]

 [[0.27277272 0.83092696 0.88471388]
  [0.72159547 0.05280036 0.73937723]]

 [[0.26256114 0.67021171 0.79063966]
  [0.25818943 0.07024232 0.49215339]]

 [[0.15551091 0.57029028 0.29036723]
  [0.3465551  0.18212896 0.39620757]]]


[0.52602156 0.48907064 0.74198116]


In [44]:
# Random integer values
np.random.randint(20, 44, size=(3,3)) # low(inclusive), high(exclusive), shape

array([[31, 40, 27],
       [37, 32, 28],
       [35, 29, 28]])

In [46]:
# The identity matrix is sequre matrix
k = np.identity(5)
print(k)
print('\n--------------------------------')
for i in range(5):
    k[i,i] = 5

print(k)
print(k.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

--------------------------------
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
float64


In [48]:
# Repeat an array
arr = np.array([[1,22,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[ 1 22  3]
 [ 1 22  3]
 [ 1 22  3]]


<img src="image/matrix.png" width=30% height=30%>

In [50]:
output = np.ones((5,5), dtype='int32')
print(output)

z = np.zeros((3,3), dtype='int32')
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Be cafeul when copying arrays!!!

In [51]:
a = np.array([1,2,3])
b = a.copy()
print(b)

b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


# Mathematics

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
a + 2

array([3, 4, 5, 6])

In [54]:
a - 2

array([-1,  0,  1,  2])

In [55]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
b = np.array([1,0,1,0])
a + b 

array([2, 2, 4, 4])

In [58]:
a ** 2

array([ 1,  4,  9, 16])

In [25]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear algebra

In [67]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

print(a.shape)
print(b.shape)

# a * b # it won't work

# matrix multiplication
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
(2, 3)
(3, 2)


array([[6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

# Statistics

In [70]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# min
np.min(stats, axis=0)

array([1, 2, 3])

In [73]:
# max
np.max(stats)

6

In [74]:
# sum
np.sum(stats)

21

In [83]:
# sum
np.sum(stats, axis=0)

array([5, 7, 9])

In [75]:
# mean
np.mean(stats)

3.5

In [80]:
d = np.arange(1, 10).reshape(3,3)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
print(np.sum(d, axis=0))
print(np.sum(d, axis=1))

[12 15 18]
[ 6 15 24]


# Reoranizing arrays


In [94]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)
print(before.ndim)

print('\n')

after = before.reshape((2,2,2))
print(after)
print(after.ndim)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


# Vertically stacking vectors

In [99]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1, v2]))
print("\n")
print(np.vstack([v1, v2, v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


# Horizontal stack

In [101]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

print("\n")

np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]




array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
**Load Data from File**

In [113]:
filedata = np.genfromtxt('data.txt', delimiter=',') # you can also specifiy dtype behind delimiter
# filedata
print(filedata)
filedata[0,0]

print("\n")

filedata.astype('int32')

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]




array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# Boolean Masking and Advanced Indexing

In [114]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [115]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [118]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])

In [119]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [120]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [121]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [125]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

<img src='image/quiz.png' width=30% height=30%>

In [130]:
quiz = np.arange(1,31).reshape(6,5)
quiz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [138]:
print(quiz[2:4, 0:2])
print(quiz[[0,1,2,3], [1,2,3,4]])
print(quiz[[0,4,5], 3:])

[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]


# Broadcasting 
Broadcasting is a powerful feature in NumPy that allows for element-wise operations between arrays of different shapes. 
It enables arrays with different dimensions to be automatically expanded or "broadcasted" to match each other's shape, allowing for convenient mathematical operations.

In [149]:
a = np.array([1,2,3])
b = np.array([[4], [5], [6]])

print(a)
print('\n')
print(b)

print('\n')
print(a.shape)
print(b.shape)

[1 2 3]


[[4]
 [5]
 [6]]


(3,)
(3, 1)


In [150]:
a + b



array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In this example, the array a has shape (3,) and the array b has shape (3, 1). Broadcasting occurs automatically, and a is expanded to match the shape of b by replicating its values along the second dimension. The element-wise addition is then performed.

Another example

```python
a = np.array([1,2,3])
b = 2
a*b #a是1维向量，b是标量，这就是形状不同
# 结果也是：[1*2,2*2, 3*2]
```

'''
这是因为发生了广播。b被填充为[2,2,2]
然后a*b的效果变成了，[1,2,3]*[2,2,2]
'''